package org.sshsqlite.jdbc;

import com.fasterxml.jackson.databind.JsonNode;

import java.sql.*;

public final class SshSqliteStatement extends BaseStatement {
    private final SshSqliteConnection connection;
    private ResultSet currentResultSet;
    private ResultSet generatedKeys;
    private long updateCount = -1;

    public SshSqliteStatement(SshSqliteConnection connection) {
        super(connection);
        this.connection = connection;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();
        ResultSet resultSet = startQuery(sql);
        currentResultSet = resultSet;
        updateCount = -1;
        return resultSet;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        clearGeneratedKeys();
        if (returnsRows(sql)) {
            currentResultSet = startQuery(sql);
            updateCount = -1;
            return true;
        }
        updateCount = executeUpdateInternal(sql, false);
        currentResultSet = null;
        return false;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        checkOpen();
        boolean returnKeys = returnGeneratedKeys(autoGeneratedKeys);
        clearGeneratedKeys();
        if (returnsRows(sql)) {
            currentResultSet = startQuery(sql);
            updateCount = -1;
            return true;
        }
        updateCount = executeUpdateInternal(sql, returnKeys);
        currentResultSet = null;
        return false;
    }

    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { checkOpen(); throw JdbcSupport.unsupported(); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { checkOpen(); throw JdbcSupport.unsupported(); }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        long count = executeLargeUpdate(sql);
        return count > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) count;
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        checkOpen();
        closeCurrentResultSet();
        clearGeneratedKeys();
        updateCount = executeUpdateInternal(sql, false);
        return updateCount;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        long count = executeLargeUpdate(sql, autoGeneratedKeys);
        return count > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) count;
    }

    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { checkOpen(); throw JdbcSupport.unsupported(); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { checkOpen(); throw JdbcSupport.unsupported(); }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        checkOpen();
        closeCurrentResultSet();
        clearGeneratedKeys();
        updateCount = executeUpdateInternal(sql, returnGeneratedKeys(autoGeneratedKeys));
        return updateCount;
    }

    @Override public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException { checkOpen(); throw JdbcSupport.unsupported(); }
    @Override public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException { checkOpen(); throw JdbcSupport.unsupported(); }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        checkOpen();
        if (generatedKeys == null) {
            generatedKeys = generatedKeysResultSet(null);
        }
        return generatedKeys;
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        checkOpen();
        return currentResultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        checkOpen();
        return updateCount > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) updateCount;
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        checkOpen();
        return updateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        checkOpen();
        closeCurrentResultSet();
        updateCount = -1;
        return false;
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        checkOpen();
        if (current != Statement.KEEP_CURRENT_RESULT) {
            closeCurrentResultSet();
        }
        updateCount = -1;
        return false;
    }

    @Override
    public void close() throws SQLException {
        closeCurrentResultSet();
        clearGeneratedKeys();
        super.close();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        checkOpen();
        return ResultSet.CONCUR_READ_ONLY;
    }

    @Override
    public int getResultSetType() throws SQLException {
        checkOpen();
        return ResultSet.TYPE_FORWARD_ONLY;
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        checkOpen();
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    int effectiveFetchSize() throws SQLException {
        int fetchSize = getFetchSize();
        return fetchSize > 0 ? fetchSize : connection.defaultFetchSize();
    }

    int queryTimeoutMs() throws SQLException {
        int seconds = getQueryTimeout();
        return seconds > 0 ? seconds * 1000 : connection.defaultQueryTimeoutMs();
    }

    SqlClient protocol() throws SQLException {
        return connection.protocol();
    }

    private ResultSet startQuery(String sql) throws SQLException {
        if (!returnsRows(sql)) {
            throw JdbcSupport.invalidArgument("executeQuery requires a statement that returns rows");
        }
        closeCurrentResultSet();
        try {
            connection.ensureTransactionForStatement();
            JsonNode response = connection.protocol().query(sql, getMaxRows(), effectiveFetchSize(), queryTimeoutMs());
            return new SshSqliteResultSet(this, response.path("cursorId").asText(), response.path("columns"));
        } catch (Exception e) {
            throw connection.sqlException(e);
        }
    }

    private long executeUpdateInternal(String sql, boolean returnGeneratedKeys) throws SQLException {
        connection.ensureWritesAllowed();
        if (returnsRows(sql)) {
            throw JdbcSupport.invalidArgument("executeUpdate requires a statement that does not return rows");
        }
        try {
            connection.ensureTransactionForStatement();
            JsonNode response = connection.protocol().exec(sql, null, queryTimeoutMs());
            if (returnGeneratedKeys) {
                generatedKeys = generatedKeysResultSet(response.path("lastInsertRowid").asLong());
            }
            return response.path("changes").asLong();
        } catch (Exception e) {
            throw connection.sqlException(e);
        }
    }

    private void closeCurrentResultSet() throws SQLException {
        if (currentResultSet != null) {
            currentResultSet.close();
            currentResultSet = null;
        }
    }

    private void clearGeneratedKeys() throws SQLException {
        if (generatedKeys != null) {
            generatedKeys.close();
            generatedKeys = null;
        }
    }

    static boolean returnGeneratedKeys(int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) return true;
        if (autoGeneratedKeys == Statement.NO_GENERATED_KEYS) return false;
        throw JdbcSupport.invalidArgument("autoGeneratedKeys must be RETURN_GENERATED_KEYS or NO_GENERATED_KEYS");
    }

    static ResultSet generatedKeysResultSet(Long lastInsertRowid) {
        java.util.List<BaseResultSetMetaData.Column> columns = java.util.List.of(
                new BaseResultSetMetaData.Column("GENERATED_KEY", "GENERATED_KEY", Types.BIGINT, "INTEGER", Long.class.getName(), false));
        java.util.List<java.util.List<Object>> rows = lastInsertRowid == null ? java.util.List.of() : java.util.List.of(java.util.List.of(lastInsertRowid));
        return new InMemoryResultSet(null, columns, rows);
    }

    static boolean returnsRows(String sql) {
        java.util.List<String> tokens = sqlTokens(sql);
        if (tokens.isEmpty()) {
            return false;
        }
        String first = tokens.get(0).toLowerCase(java.util.Locale.ROOT);
        if (first.equals("select") || first.equals("pragma") || first.equals("values") || first.equals("with")) {
            return true;
        }
        for (String token : tokens) {
            if (token.equalsIgnoreCase("returning")) {
                return true;
            }
        }
        return false;
    }

    private static java.util.List<String> sqlTokens(String sql) {
        java.util.ArrayList<String> tokens = new java.util.ArrayList<>();
        StringBuilder current = new StringBuilder();
        boolean lineComment = false;
        boolean blockComment = false;
        char quote = 0;
        for (int i = 0; i < sql.length(); i++) {
            char ch = sql.charAt(i);
            if (lineComment) {
                if (ch == '\n' || ch == '\r') lineComment = false;
                continue;
            }
            if (blockComment) {
                if (ch == '/' && i > 0 && sql.charAt(i - 1) == '*') blockComment = false;
                continue;
            }
            if (quote != 0) {
                if (ch == quote) {
                    if (quote == '\'' && i + 1 < sql.length() && sql.charAt(i + 1) == '\'') {
                        i++;
                        continue;
                    }
                    quote = 0;
                }
                continue;
            }
            if (ch == '-' && i + 1 < sql.length() && sql.charAt(i + 1) == '-') {
                flushToken(tokens, current);
                lineComment = true;
                continue;
            }
            if (ch == '/' && i + 1 < sql.length() && sql.charAt(i + 1) == '*') {
                flushToken(tokens, current);
                blockComment = true;
                continue;
            }
            if (ch == '\'' || ch == '"' || ch == '`') {
                flushToken(tokens, current);
                quote = ch;
                continue;
            }
            if (Character.isLetter(ch) || ch == '_') {
                current.append(ch);
            } else {
                flushToken(tokens, current);
            }
        }
        flushToken(tokens, current);
        return tokens;
    }

    private static void flushToken(java.util.List<String> tokens, StringBuilder current) {
        if (current.length() > 0) {
            tokens.add(current.toString());
            current.setLength(0);
        }
    }
}
